### ISSUE TITLE
Update node centers the node briefly

### ISSUE THREAD

**Issue by superawe** [anvaka/VivaGraphJS#149]
Hi!

I am using VivaGraph in my project and really like it.
However there is an issue with addNode in Safari and on iOS-device browsers that I cannot fix.
All added nodes (no matter new or already existing) appear at the center of the graph for 1 frame or so and then finds their correct positions.
This is a video screen capture of the completely unmodified dynamic node change example from latest release:
https://www.youtube.com/watch?v=U3P20b9jzCc

It all seems to work well in Chrome and Firefox though.

Best regards,
Arvid Sahlin

**Comment by anvaka** [comment]
Hi Arvid,

Thanks for reporting this. I can reproduce it and will look at the problem later today.

**Comment by anvaka** [comment]
Should be fixed by [this commit](https://github.com/anvaka/VivaGraphJS/commit/1422d87a300cff22187c4e00570c3432897d5564): [Demo](https://anvaka.github.io/VivaGraphJS/demos/other/dynamicNodeChange.html)

Apparently when graph changes I completely destroy old UI and recreate a new one. I don't think that is necessary, but this is a quick workaround for a problem.

I will try to address partial change in the future.

**Comment by bitjoy** [comment]
Thank you!
Works like a charm!
