### ISSUE TITLE
jsFiddle example from /docs/graph_intro.md don't work 

### ISSUE THREAD

**Issue by AmberDeBlack** [anvaka/VivaGraphJS#160]
Checked on 

Chrome 44.0.2403.157 m on Windows 10
Chrome 44.0.2403.157 (64-bit) on OS X

Link:
http://jsfiddle.net/anvaka/JA76K/2/

**Comment by anvaka** [comment]
Wow, I can't believe it's been four years since I started the library:

![image](https://cloud.githubusercontent.com/assets/225407/9596974/2aaca96c-5031-11e5-9c6a-dd1dcaed6556.png)

Thanks for reporting this! The library went through so many changes, and now is constructed from small modules. Each of [these modules](https://github.com/anvaka/VivaGraphJS/blob/d65150bfd42afba7d9bb4b3884b0bb2c99ad8c55/package.json#L35-L45) have documentation on their own repository and I forgot about `docs` folder here.

Anyway, I updated `docs` here and now it should point to working jsfiddle: http://jsfiddle.net/JA76K/182/
