### ISSUE TITLE
Bake/save generated graph layouts

### ISSUE THREAD

**Issue by andymikulski** [anvaka/VivaGraphJS#172]
When creating a graph with many nodes, they all spawn from the center of the graph and take a second to get into correct position. Example:

![image](http://i.imgur.com/xQDgzUR.gif)

Is there any way to generate and save the 'final' at-rest graph, so it can be displayed again later? I'd love to find a way to just have the graph ready to go on the page, versus having it unfold each time.

**Comment by andymikulski** [comment]
Found the answer![0] Sorry for the unnecessary issue.

[0] https://github.com/anvaka/VivaGraphJS/blob/077fa7fa6846bf4c86a3a8c32a7867bf4339cbed/demos/other/precompute-advanced.html

**Comment by anvaka** [comment]
Glad you found the solution @andymikulski! You can also use constant layout if you already have your positions saved somewhere, so that clients will not have to recompute it all the time. Here is an example: https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/constantLayout.html

Just as another tip - sigma.js is perfect for constant layouts too, may be worth exploring if it suites your case better: http://sigmajs.org/
