### ISSUE TITLE
Detect end of initial renderization

### ISSUE THREAD

**Issue by mauriciogior** [anvaka/VivaGraphJS#196]
Is there a way to detect when the layout is renderized, or detect the amount of frames/steps the renderer already processed?

Since I have disconnected node trees, I need to pause the renderer after a certain time so they do not be too far away from each other. Is there a way to close the gap between disconnected trees as well?

Thanks.

**Comment by anvaka** [comment]
If graph is small and it converges, then you can listen to force based layout to fire a [`stable` event](https://github.com/anvaka/ngraph.forcelayout/blob/0b9bfc190b93002465b43477c5dd49a3ef50fb0b/index.js#L208).

Otherwise if graph has lots of movement, you can get amount of movement by querying layout's  [`lastMove` property](https://github.com/anvaka/ngraph.forcelayout/blob/0b9bfc190b93002465b43477c5dd49a3ef50fb0b/index.js#L163-L166)

I don't think there is a trivial way to keep disconnected trees together. One workaround could be rendering each individual subgraph separately, though it may not be applicable to your requirements.

**Comment by mauriciogior** [comment]
For anyone wondering, I kinda fixed using `stableThreshold: 15`.
