### ISSUE TITLE
Cannot set attribute xlink:href

### ISSUE THREAD

**Issue by atima** [anvaka/VivaGraphJS#66]
I try to add text to path with textPath, which requires xlink:href attribute. However, the code seem to be corrupted. This happens whenever I set xlink:href.

For example,
svgText = Viva.Graph.svg('text').attr('y', '-4px').attr('xlink:href', 'www.google.com').text(node.id),

will render nothing.

Any Idea?

**Comment by karthim** [comment]
Hi, 

Thanks for example code showing how to add edge label. When you remove the link using graph.removeLink method, the label is not getting removed. It stays in the graph. Do you have any suggestion on how to link the label with the edge so that when we remove the edge the label also gets removed.

Regards,
Karthic

**Comment by VladBrok** [comment]
> Thanks for your help. I use text transforms as the suggestion.
> 
> Here is the example code for someone who may interest in link label creation: http://jsfiddle.net/atima/yc3tB/7/

@atima thank you
