### ISSUE TITLE
Text for webgl nodes

### ISSUE THREAD

**Issue by aecepoglu** [anvaka/VivaGraphJS#86]
Has anyone spent any time trying to show text for webgl nodes?

My webgl knowledge is very limited, but I have been able to draw texts to a seperate canvas and load that as a texture. I am guessing one could create a texture for each node, and create a new function in webglUIModel that would draw draw a texture for a node.

I haven't been able to do that though. Has anyone?

**Comment by valtih1978** [comment]
Stackexchange says that [rendering text in WebGL must not be answered in Vivagraph context because it is not clear what people are asking](http://stackoverflow.com/questions/28373796). In other words, you should not answer what you did and keep your knowledge alone. Stackexchange is a collection of superior first-class word experts and they know better in programming community.

**Comment by danpaulsmith** [comment]
The fastest and best looking way to draw text in WebGL is using Signed Distance Fields.  You need to draw two triangles as a square/quad and then attach the letter as an image. The second step is to allow scaling, so you need a shader program that uses the images black/white/alpha channel to discard certain pixels that fall outside the desired range, creating a crisp letter. I'd be happy to help incorporate SDF font rendering for VivaGraph if I have some time.

**Comment by mzachariadis** [comment]
Hello! Is there any update on this issue? DOM based labels is not the best solution when you have a big batch of nodes.

**Comment by aecepoglu** [comment]
It has been a long time since I used this tool and don't recall if this is an issue. Reopen if you still need this
